export const GET_SHOES_REQUEST = "GET_SHOES_REQUEST";
export const GET_SHOES_SUCCESS = "GET_SHOES_SUCCESS";
export const GET_SHOES_FAIL = "GET_SHOES_FAIL";

export const GET_SHOE_DETAILS_REQUEST = "GET_SHOE_DETAILS_REQUEST";
export const GET_SHOE_DETAILS_SUCCESS = "GET_SHOE_DETAILS_SUCCESS";
export const GET_SHOE_DETAILS_FAIL = "GET_SHOE_DETAILS_FAIL";
export const GET_SHOE_DETAILS_RESET = "GET_SHOE_DETAILS_RESET";